export const INTRO_BPM = 72;
export const INTRO_STEPS_PER_BEAT = 4;
export const INTRO_STEPS_PER_SCENE = 32;
export const INTRO_SCENE_COUNT = 5;
export const INTRO_BEATS_PER_SCENE = INTRO_STEPS_PER_SCENE / INTRO_STEPS_PER_BEAT;
export const INTRO_SCENE_SECONDS = INTRO_BEATS_PER_SCENE * (60 / INTRO_BPM);
export const INTRO_LOOP_SECONDS = INTRO_SCENE_SECONDS * INTRO_SCENE_COUNT;
